In [49]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
import pandas as pd
import numpy as np

In [50]:
df=pd.read_csv(r'C:\Users\devan\nlp\train.csv')
df

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [51]:
df=df.drop(columns=['keyword','id','location'])

In [52]:
df

                                                   text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
...                                                 ...     ...
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [53]:
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [54]:
df.copy()
y=df['target']
y

0       1
1       1
2       1
3       1
4       1
       ..
7608    1
7609    1
7610    1
7611    1
7612    1
Name: target, Length: 7613, dtype: int64

In [55]:
texts=df['text']
texts.shape[0]

7613

In [56]:
import re
corpus=[]
text=df['text']
for i in text:
    review = re.sub('[^a-zA-Z]', ' ', i)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review ]
    review = ' '.join(review)
    corpus.append(review)

In [57]:
corpus

['our deed are the reason of thi earthquak may allah forgiv us all',
 'forest fire near la rong sask canada',
 'all resid ask to shelter in place are be notifi by offic no other evacu or shelter in place order are expect',
 'peopl receiv wildfir evacu order in california',
 'just got sent thi photo from rubi alaska as smoke from wildfir pour into a school',
 'rockyfir updat california hwi close in both direct due to lake counti fire cafir wildfir',
 'flood disast heavi rain caus flash flood of street in manit colorado spring area',
 'i m on top of the hill and i can see a fire in the wood',
 'there s an emerg evacu happen now in the build across the street',
 'i m afraid that the tornado is come to our area',
 'three peopl die from the heat wave so far',
 'haha south tampa is get flood hah wait a second i live in south tampa what am i gonna do what am i gonna do fvck flood',
 'rain flood florida tampabay tampa or day i ve lost count',
 'flood in bago myanmar we arriv bago',
 'damag to school bu on in multi car crash break',
 'what s up man',
 'i love fruit',
 'summer is love',
 'my car is so fast',
 'what a goooooooaaaaaal',
 'thi is ridicul',
 'london is cool',
 'love ski',
 'what a wonder day',
 'looooool',
 'no way i can t eat that shit',
 'wa in nyc last week',
 'love my girlfriend',
 'cooool',
 'do you like pasta',
 'the end',
 'bbcmtd wholesal market ablaz http t co lhyxeohi c',
 'we alway tri to bring the heavi metal rt http t co yao e xngw',
 'africanbaz break news nigeria flag set ablaz in aba http t co nndbgwyei',
 'cri out for more set me ablaz',
 'on plu side look at the sky last night it wa ablaz http t co qqsmshaj n',
 'phdsquar mufc they ve built so much hype around new acquisit but i doubt they will set the epl ablaz thi season',
 'inec offic in abia set ablaz http t co imaomknna',
 'barbado bridgetown jamaica two car set ablaz santa cruz head of the st elizabeth polic superintend http t co wdueaj q j',
 'ablaz for you lord d',
 'check these out http t co roi nsmejj http t co tj zjin http t co yduixefip http t co lxtjc kl nsfw',
 'on the outsid you re ablaz and aliv but you re dead insid',
 'had an awesom time visit the cfc head offic the ancop site and ablaz thank to tita vida for take care of us',
 'soooo pump for ablaz southridgelif',
 'i want to set chicago ablaz with my preach but not my hotel http t co o qknbfofx',
 'i gain follow in the last week you know your stat and grow with http t co tiyulif c',
 'how the west wa burn thousand of wildfir ablaz in california alon http t co vl tbr wbr',
 'build the perfect tracklist to life leav the street ablaz',
 'check these out http t co roi nsmejj http t co tj zjin http t co yduixefip http t co lxtjc kl nsfw',
 'first night with retain in it s quit weird better get use to it i have to wear them everi singl night for the next year at least',
 'deputi man shot befor brighton home set ablaz http t co gwnrhmso k',
 'man wife get six year jail for set ablaz niec http t co ev ahoucza',
 'santa cruz head of the st elizabeth polic superintend lanford salmon ha r http t co vplr hka u http t co sxhw tnnlf',
 'polic arsonist deliber set black church in north carolina ablaz http t co pcxarbh an',
 'noch el bestia alexi sanchez happi to see my teammat and train hard goodnight gunner http t co uc j jhvgr',
 'kurd trampl on turkmen flag later set it ablaz while other vandal offic of turkmen front in diyala http t co izfdyc cg',
 'truck ablaz r voortrekk ave outsid or tambo intl cargo section http t co kscqkfkkf',
 'set our heart ablaz and everi citi wa a gift and everi skylin wa like a kiss upon the lip http t co cyompz a z',
 'they sky wa ablaz tonight in lo angel i m expect ig and fb to be fill with sunset shot if i know my peep',
 'how the west wa burn thousand of wildfir ablaz in california alon http t co icsjgz te climat energi http t co fxmn l bd',
 'revel in your wmv video by mean of mac farewel ablaz wmv en rout to dvd gtxrwm',
 'progress greet in about a month student would have set their pen ablaz in the torch public http t co fxpixqujt',
 'rene ablaz amp jacinta secret k fallen sky edit mar http t co mlmsuzv z',
 'navista steve these fire out here are someth els california is a tinderbox and thi clown wa set my hood ablaz news',
 'nowplay rene ablaz amp ian buff magnitud http t co av jsjfftc edm',
 'nxwestmidland huge fire at wholesal market ablaz http t co rwzbfvnxer',
 'ablaz what time doe your talk go until i don t know if i can make it due to work',
 'i can t have kid cuz i got in a bicycl accid amp split my testicl it s imposs for me to have kid michael you are the father',
 'accid on i w nashvilletraff traffic move m slower than usual http t co ghk egj',
 'accid center lane block in santaclara on us nb befor great america pkwi bayarea traffic http t co pmlohzurwr',
 'http t co gkye gjtk had a personalinjuri accid thi summer read our advic amp see how a solicitor can help otleyhour',
 'stloui caraccidentlawy speed among top caus of teen accid http t co k zomof http t co s kxvm cba car accid tee',
 'report motor vehicl accid in curri on herman rd near stephenson involv an overturn vehicl pleas use http t co ybjezkurw',
 'bigrigradio live accid awar',
 'i mile marker south mooresvil iredel vehicl accid ramp close at pm',
 'rt sleepjunki sleep pill doubl your risk of a car accid http t co s nm fict',
 'by accid they knew what wa gon happen http t co ysxun vceh',
 'traffic accid n cabrillo hwi magellan av mir',
 'i mile marker to south mooresvil iredel vehicl accid congest at pm',
 'the pastor wa not in the scene of the accid who wa the owner of the rang rover',
 'mom we didn t get home as fast as we wish me whi is that mom there wa an accid and some truck spilt mayonnais all over',
 'i wa in a horribl car accid thi past sunday i m final abl to get around thank you god',
 'can wait to see how piss donni is when i tell him i wa in anoth accid',
 'truckcrash overturn on fortworth interst http t co rs lj qfp click here if you ve been in a crash gt http t co ld uniyw k',
 'accid in ashvil on us sb befor sr traffic http t co hylmo wgfi',
 'carolina accid motorcyclist die in i crash with car that cross median a motorcycl rider travel http t co p lzrlmi',
 'fyi cad fyi accid properti damag nh piner rd horndal dr',
 'rt naayf first accid in year turn onto chandane magu from near mma taxi ram into me while i wa halfway turn everyon conf',
 'accid left lane block in manchest on rt nb befor eddi rd stop and go traffic back to nh a delay of min traffic',
 'accid properti damag piner rd horndal dr',
 'it wa an accid http t co oia fxi gm',
 'fyi cad fyi accid properti damag wpd s th st',
 'pm traffic accid no injuri at willi foreman rd http t co vckit edev',
 'aashiqui actress anu aggarw on her near fatal accid http t co otfp lqw',
 'suffield alberta accid http t co bptmlf p',
 'mile backup on i south accid block the right lane at exit langtre rd consid nc or nc to nc as altern',
 'ha an accid chang your life we will help you determin option that can financi support life care plan and on go treatment',
 'break there wa a deadli motorcycl car accid that happen to hagerstown today i ll have more detail at your state whag',
 'flowri were you marinad it or wa it an accid',
 'onli had a car for not even a week and got in a fuck car accid mf can t fuck drive',
 'norwaymfa bahrain polic had previous die in a road accid they were not kill by explos http t co gfjfgtodad',
 'i still have not heard church leader of kenya come forward to comment on the accid issu and disciplinari measur arrestpastornganga',
 'aftershock delo scuf ps live and the game cya',
 'the man who can drive himself further onc the effort get pain is the man who will win roger bannist',
 'ir icemoon aftershock http t co ynxnvvkcda djicemoon dubstep trapmus dnb edm danc ice http t co weqpesenku',
 'there is no victori at bargain basement price dwight david eisenhow',
 'ir icemoon aftershock http t co vam podgyw djicemoon dubstep trapmus dnb edm danc ice http t co zevakjapcz',
 'nobodi rememb who came in second charl schulz',
 'aftershock delo im speak from someon that is use a scuf on xb most of them peopl will end up get on for ps also',
 'the harder the conflict the more gloriou the triumph thoma pain',
 'growingupspoil go clay pigeon shoot and cri becaus of the aftershock',
 'so i guess no one actual want ani free aftershock tc',
 'aftershock wa the most terrifi best roller coaster i ve ever been on disclaim i ve been on veri few',
 'aftershock http t co xmwodfmtui',
 'ir icemoon aftershock http t co m jdzmgjow djicemoon dubstep trapmus dnb edm danc ice http t co n uhasfkbv',
 'ir icemoon aftershock http t co vam podgyw djicemoon dubstep trapmus dnb edm danc ice http t co zevakjapcz',
 'ir icemoon aftershock http t co e epzhoth djicemoon dubstep trapmus dnb edm danc ice http t co a d do q',
 'kjforday i m see them and issu at aftershock',
 'ir icemoon aftershock http t co thyzomvwu djicemoon dubstep trapmus dnb edm danc ice http t co joo xk',
 'ir icemoon aftershock http t co thyzomvwu djicemoon dubstep trapmus dnb edm danc ice http t co joo xk',
 'wisdomw bonu minut daili habit that could realli improv your life how mani do you alreadi do lifehack http t co tbm fqb cw',
 'aftershock protect yourself and profit in the next global financi meltdown by david wiedem http http t co wztz hgmvq',
 'that moment when you get on a scari roller coaster and the guy behind you is just scream bloodi murder silverwood aftershock',
 'aftershock full stream youtub http t co vve usesgf',
 'gt gt aftershock protect yourself and profit in the next global financi book http t co f ntuc z esquireattir',
 'sometim you face difficulti not becaus you re do someth wrong but becaus you re do someth right joel osteen',
 'the onli thing that stand between you and your dream is the will to tri and the belief that it is actual possibl joel brown',
 'prais god that we have ministri that tell it like it is now wdyouth biblestudi http t co ujk e gbcc',
 'rememb that you are go to die is the best way i know to avoid the trap of think you have someth to lose steve job',
 'tri orang aftershock today my life will never be the same',
 'onfireand i love you bb',
 'aftershock http t co jv ppkhji',
 'aftershock back to school kick off wa great i want to thank everyon for make it possibl what a great night',
 'peopl who say it cannot be done should not interrupt those who are do it georg bernard shaw',
 'the first man get the oyster the second man get the shell andrew carnegi',
 'anyon need a p u tonight i play hybrid slayer ps eu hmu cod sandscrim empirikgam codawscrim tp kotc tpfa aftershock org',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert o http t co yvvpznzmxg news',
 'strict liabil in the context of an airplan accid pilot error is a common compon of most aviat cr http t co cz bohrd',
 'crobscarla your lifetim odd of die from an airplan accid are in',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert on wedn http t co bkpfpogysi',
 'alexalltimelow awwww they re on an airplan accid and they re gonna die what a cuti good job',
 'famili member of osama bin laden have die in an airplan accid how iron mhmmm gov shit i suspect',
 'man goe into airplan engin accid http t co tyjxrfd st via youtub',
 'horribl accid man die in wing of airplan http t co i kztevb v',
 'a cessna airplan accid in ocampo coahuila mexico on juli kill four men includ a state of coahuila govern offici',
 'horribl accid man die in wing airplan watchthevideo http t co p xrvgjik',
 'expert in franc begin examin airplan debri found on reunion island http t co lsmx vwr j french air accid expert on wednesday',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert on wednesday began examin t',
 'kca votejkt id mbataweel rip binladen famili member who kill in an airplan s accid',
 'i almost sent my cowork nude on accid thank god for airplan mode',
 'mickinyman theatlant that or they might be kill in an airplan accid in the night a car wreck polit at it s best',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert on http t co tagzbcxfj mlb',
 'thi is unbeliev insan man airport airplan aircraft aeroplan runway accid freaki http t co cezhq czll',
 'horribl accid man die in wing of airplan http t co wq wjsgphl',
 'horribl accid man die in wing of airplan http t co tfcdronra',
 'usama bin ladin famili dead in airplan crash natur no accid',
 'pilot die in plane crash at car festiv http t co kq ae ap b via youtub crash aircraft airplan pilot death accid carfest',
 'strict liabil in the context of an airplan accid http t co gibyqhhkpk',
 'dtn brazil expert in franc begin examin airplan debri found on reunion island french air accid exp http t co m ig wq lq',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert on wedn http t co v smaeslk',
 'horribl accid man die in wing of airplan wtf you can t believ your eye http t co ffylajwp',
 'nicol fletcher one of a victim of crash airplan few time ago the accid left a littl bit trauma for her although she s',
 'omg horribl accid man die in wing of airplan http t co xdxdprcpn',
 'omg i don t believ thi rip bro airplan accid jetengin turbojet bo g http t co kxxnszp nk',
 'expert in franc begin examin airplan debri found on reunion island french air accid expert on wednesday began examin t',
 'i had a airplan accid',
 'my phone look like it wa in a car ship airplan accid terribl',
 'statist i m at more of risk of get kill by a cop than i am of die in an airplan accid',
 'airplan crash on hous in colombia peopl die in accid http t co zhjlflbhzl',
 'the shoot or the airplan accid http t co iecc jdoub',
 'could a drone caus an airplan accid pilot worri about use of drone esp in close vicin of airport http t co kz rgngjf',
 'earli wake up call from my sister beg me to come over amp ride w her in the ambul to the hospit rodkiai',
 'http t co ay zzcupnz twelv fear kill in pakistani air ambul helicopt crash http t co sc dn mc',
 'two air ambul on scene of seriou crash between two car and lorri in http t co pfeaqeski http t co fntg rnkx emsn',
 'twelv fear kill in pakistani air ambul helicopt crash reuter http t co mdnugvubwn yugvani',
 'lead emerg servic boss welcom new ambul chariti http t co mj jq psv',
 'anyon travel aberystwyth shrewsburi right now there s been an incid servic at a halt just outsid shrew ambul on scene',
 'twelv fear kill in pakistani air ambul helicopt crash http t co xum ylcb q',
 'ambul sprinter automat frontlin vehicl choic of lez compliant ebay http t co evttqpeia',
 'new nanotech devic will be abl to target and destroy blood clot http t co hfi v slbb',
 'skyhawkmm traplord fredosantana lilrees it wa hella crazi fight an ambul and a coupl mosh pit',
 'if i get run over by an ambul am i lucki justsay randomthought',
 'news twelv fear kill in pakistani air ambul helicopt crash http t co bfe twbzt til now dna',
 'http t co xglah zl twelv fear kill in pakistani air ambul helicopt crash http t co thmblaatzp',
 'tanslash wait for an ambul',
 'fouseytub you ok need a ambul hahahah that wa good http t co zsberqnn n',
 'ambul sprinter automat frontlin vehicl choic of lez compliant ebay http t co q ivrzojzv',
 'pakistan air ambul helicopt crash kill nine http t co e ry ebmf',
 'thenissonian rejectdcartoon nissan are you ok do you need medic assist i can call an ambul if you need me to',
 'em ny emt petit for per hour minimum wage http t co oa swlxmr em paramed ambul',
 'http t co fcqmkffflw twelv fear kill in pakistani air ambul helicopt crash http t co vayaymbngu',
 'twelv fear kill in pakistani air ambul helicopt crash http t co brme sn t',
 'ambul sprinter automat frontlin vehicl choic of lez compliant ebay http t co ujrx kgawp',
 'ambul sprinter automat frontlin vehicl choic of lez compliant ebay http t co kp lf aut',
 'kiwi karyn check out what s in my park lot he said that until last year it wa an ambul in st john http t co hpvodud ip',
 'when you don t know which way an ambul is come from lt lt',
 'reuter twelv fear kill in pakistani air ambul helicopt crash http t co shzpyiqok',
 'http t co pwwpum rbj twelv fear kill in pakistani air ambul helicopt crash http t co yspon d qo',
 'whi is there an ambul right outsid my work',
 'leoblakecart thi dog think he s an ambul http t co mg lpgr rm natasha rideout',
 'happen now hatzolah em ambul respond with dual siren and http t co sek mq njf',
 'http t co fuerk gwui twelv fear kill in pakistani air ambul helicopt crash http t co mv ggglmvc',
 'http t co x yeuylt x twelv fear kill in pakistani air ambul helicopt crash http t co ugrmd z n',
 'twelv fear kill in pakistani air ambul helicopt crash http t co th ywbbeet worldnew',
 'twelv fear kill in pakistani air ambul helicopt crash http t co x qsjod u worldnew',
 'what s the polic or ambul number in lesotho ani bodi know',
 'medic aac org i am surpris we still cannot standardis the clinic practic across the nh ambul trust',
 'http t co j tyt xrrk twelv fear kill in pakistani air ambul helicopt crash http t co d nazoi',
 'peopl who tri to j walk while an ambul is pass i hate you',
 'the episod where trunk annihil freiza is the cleanest shit ever he show that nigga no merci',
 'they shall be annihil and all of their petebest dessic and laid bare then you shall kneel befor me',
 'urib just annihil that basebal met',
 'marksmaponyan hey sundown were annihil in their previou meet with celtic inde it an improv',
 'volfan tneazzi mizzou ha annihil florida the past season even end muschamp s career just can t compet with bama',
 'annihil ab http t co xpw tje',
 'be annihil for statu educ mba on behalf of a on easi street careen eovm http t co e pi c ff',
 'to luka they should all die all of them everyth annihil aloi tranci',
 'acarewornheart have a good un fella sorri i won t be there to get annihil with you',
 'cop pull drunk driver to safeti second befor hi car is hit by train http t co thrhkhogcu http t co tzszmf qxe via viralspel',
 'you must be annihil',
 'cop pull drunk driver to safeti second befor hi car is hit by train http t co c nkgp w http t co imwmfdjssn via viralspel',
 'boom your countri wa just entir annihil by a h britain http t co irfcn szv',
 'amirkingkhan you would have been annihil so you might as well thank floydmayweath',
 'one thing for sure god ha promis israel will not be annihil but the horror of iran w nuke http t co xn mx sxi',
 'violentfeminazi i guess that s ok for armenian sinc we ve spent most of our histori get annihil',
 'year sinc we annihil peopl instantli and becam awar that we have the abil to annihil the whole of human',
 'day of tryout went good minu the fact i stop quickli to get a short ball and annihil my toenail injuri even more',
 'dure the s the oryx a symbol of the arabian peninsula were annihil by hunter http t co yangeqbuqw http t co jq eh kglt',
 'to luka they should all die all of them everyth annihil aloi tranci',
 'readi to get annihil for the buc game',
 'philipduncan breakfaston peopl annihil by last night weather realli philip thought you would have forecast that',
 'domain other sophist be annihil close up to the minut feat zrnf',
 'stormbeard steel lord i seen juda priest in when rob came back scorpion as support fuck annihil the place astonish gig',
 'offici skip out on fantasticfour fant stic whatev the hashtag is it s get annihil in review bummer',
 'tomcatart thu explain whi you were all annihil but the few or in thi case you the onli survivor evolv and becam godlik',
 'just complet annihil cech with paul keegan what a time to be aliv',
 'tomcatart who then were annihil by the legion itself the survivor of the imperfect hybrid project quickli form a new secret cell',

In [58]:
cv = CountVectorizer(max_features=2500)

x = cv.fit_transform(corpus).toarray()

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [60]:
import lightgbm as lgbm
model = lgbm.LGBMClassifier(n_estimators=255,max_depth=12,learning_rate=0.095)
model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 2634, number of negative: 3456
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007845 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1900
[LightGBM] [Info] Number of data points in the train set: 6090, number of used features: 704
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.432512 -> initscore=-0.271608
[LightGBM] [Info] Start training from score -0.271608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(learning_rate=0.095, max_depth=12, n_estimators=255)

In [61]:

y_pred=model.predict(X_test)

C:\Users\devan\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [62]:
from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
print(score)

0.8003939592908733

In [63]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.89      0.79      0.84      1000
           1       0.67      0.82      0.74       523

    accuracy                           0.80      1523
   macro avg       0.78      0.80      0.79      1523
weighted avg       0.82      0.80      0.80      1523